import { getRequiredEnv } from "./playwrightEnv";

export const PLAYWRIGHT_FRONTEND_PORT = 4174;
export const PLAYWRIGHT_BACKEND_PORT = 4001;

export const PLAYWRIGHT_FRONTEND_ORIGIN = `http://127.0.0.1:${PLAYWRIGHT_FRONTEND_PORT}`;
export const PLAYWRIGHT_BACKEND_ORIGIN = `http://127.0.0.1:${PLAYWRIGHT_BACKEND_PORT}`;
export const PLAYWRIGHT_BACKEND_RPC_URL = `${PLAYWRIGHT_BACKEND_ORIGIN}/rpc`;

export const PLAYWRIGHT_ALLOWED_FRONTEND_ORIGINS = [
  PLAYWRIGHT_FRONTEND_ORIGIN,
  `http://localhost:${PLAYWRIGHT_FRONTEND_PORT}`,
].join(",");

export const PLAYWRIGHT_CAPTCHA_BYPASS_CODE = getRequiredEnv(
  "PLAYWRIGHT_CAPTCHA_BYPASS_CODE"
);
