name: Trigger Cloudflare Pages Deploy Hook

on:
  push:
    tags:
      - "*" # triggers on push to any tag

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Deploy Hook
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"
